---
Mappings:
  RegionEC2InstanceImageMap:
    us-east-2:
      HVM64: ami-02de934ca4f3289e0 
      HVM32: ami-0233c2d874b811deb
    ap-southeast-2:
      HVM64: ami-0e040c48614ad1327
      ARM64: ami-0ec6a2b0e8862d01e

Parameters:
  EC2InstanceType:
    Description: The Instance Type Chosen for EC2
    Type: String
    
Resources:
  TekLoonTestInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: ap-southeast-2a
      ImageId: !FindInMap
        - RegionEC2InstanceImageMap
        - !Ref 'AWS::Region'
        - HVM64
      InstanceType: !Ref EC2InstanceType
      SecurityGroups:
        - !Ref HTTPSecurityGroup

  HTTPSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable port 80 and port 443
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 80
        IpProtocol: tcp
        ToPort: 80
      - CidrIp: 0.0.0.0/0
        FromPort: 443
        IpProtocol: tcp
        ToPort: 443
